dist: trusty
sudo: false
language: php

php:
  - 7.4

before_install:
  - composer self-update

jobs:
  include:
    - stage: Test
      php: 7.4
      install: travis_retry composer install --prefer-dist
      script:
        - ./vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache
