name: "PHPUnit tests"
on:
  pull_request:
  push:
    branches:
      - "master"
      - "3.x"
jobs:
  phpunit:
    name: "PHPUnit tests"
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        dependencies:
          - "lowest"
          - "highest"
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        operating-system:
          - "ubuntu-latest"
          - "windows-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "pcov"
          php-version: "${{ matrix.php-version }}"
          ini-values: memory_limit=-1
      - name: "Install lowest dependencies"
        uses: "ramsey/composer-install@v3"
        if: ${{ matrix.dependencies == 'lowest' }}
        with:
          composer-options: "--prefer-lowest --no-interaction --no-progress --no-suggest"
      - name: "Install highest dependencies"
        uses: "ramsey/composer-install@v3"
        if: ${{ matrix.dependencies == 'highest' }}
        with:
          composer-options: "--no-interaction --no-progress --no-suggest"
      - name: "Tests"
        run: "vendor/bin/phpunit --fail-on-warning"
